apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: devops-app
type: Opaque
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: appuser@123   # Change this before deploying
  POSTGRES_DB: appdb
  DATABASE_URL: postgres://appuser:appuser@123@postgres-service:5432/appdb